### ISSUE TITLE
Restart Workers on File Changes

### ISSUE THREAD

**Issue by mnavarrocarter** [spiral/roadrunner#102]
It would be pretty cool to include something that works like Nodemon in this library: a process that scans for `*.php` file changes in the root folder of the project and then restarts the workers if any change in code is encountered.

It could be optional and configurable in the `yaml` file. Suggestion:

```yaml
hot-reload:
    enabled: true
    root_dir: ./ # relative to the rr.yaml file 
    rule: *.php # matches any php file.
```

I know a little bit of Go, so I could give it a try. I imagine the way to implement this is a goroutine that is dispatched every x seconds, checks for changes, and restarts the worker if any change is made.
