### ISSUE TITLE
Performance degradation on production

### ISSUE THREAD

**Issue by 4n70w4** [spiral/roadrunner#132]
PHP 7.3 / Symfony 3.4

Hi! On local dev server i get x 2-10-20 request time speed up for 1 concurrency request.

But on production for 50 concurent request performance on FPM 180 requests per second, on RR 165 rps. If add gc_collect_cycles() for each cycle - perfomance for RR down to 140 rps...

It is strange, there are ideas why it can work slower than FPM?

`ab -n 10000 -k -c 50 ...`

Enable/disablee keep alive; direct connect to roadrunner port or nginx proxypass do not affect performance.

config:

```
http:
  address: 0.0.0.0:8080
  workers:
    command: "php /var/www/app/current/worker.php"
  pool:
    numWorkers: 8
    maxJobs: 0
```

`bin/rr serve -c roadrunner.prod.yaml`

With numWorkers: 50 and maxJobs: 200 the same perfomance.

Processor: AMD Ryzen Pro 1700x (8 x 3,4 GHz)
RAM: 32 GB DDR4
