### ISSUE TITLE
Can not restart a pool that run on linux from under Windows

### ISSUE THREAD

**Issue by speller** [spiral/roadrunner#154]
Hello,
My host machine is Windows 10. I run a docker Linux container with RR. The RR ports 6000 and 6001 are reachable from under the Windows host machine. But trying to restart the pool from under the Windows CLI leads to the following error:

```
C:\***>rr -c C:\***\rr.yml http:reset -l flat
Restarting http worker pool: Error: unexpected EOF
```

The pool is not restarted in the result. The config file is the same as inside the container.

I suppose that RR binary protocols are not identical under Linux and Windows and should be fixed.

**Comment by wolfy-j** [comment]
The protocols are identical, I assume there can be some interruption in Docker network. Do Any other command work?

**Comment by speller** [comment]
XDebug works fine inside the same container, port 80 also is fine.

**Comment by wolfy-j** [comment]
The reset command works fine between the host machine and docker on my system (Windows). Please share some way to reproduce the issue.

**Comment by speller** [comment]
Here is my configuration:

Dockerfile:
```
FROM php:7.3-cli

ARG rr_version=1.4.2

WORKDIR /workdir

RUN apt-get update -y \
	&& apt-get install -y netselect-apt

RUN netselect-apt -o /etc/apt/sources.list.n -c NZ \
	&& rm /etc/apt/sources.list \
	&& mv /etc/apt/sources.list.n /etc/apt/sources.list

RUN apt-get update -y \
	&& apt-get install -y imagemagick

RUN wget -q https://github.com/spiral/roadrunner/releases/download/v${rr_version}/roadrunner-${rr_version}-linux-amd64.tar.gz \
    && tar xvzf roadrunner-${rr_version}-linux-amd64.tar.gz \
    && cp roadrunner-${rr_version}-linux-amd64/rr /bin/rr \
    && rm -rf roadrunner-${rr_version}-linux-amd64 \
    && unlink roadrunner-${rr_version}-linux-amd64.tar.gz

RUN apt-get install -y \
		libzip-dev \
		libicu-dev \
	&& docker-php-ext-install -j$(nproc) zip \
	&& docker-php-ext-install -j$(nproc) pdo_mysql \
	&& docker-php-ext-configure intl \
	&& docker-php-ext-install -j$(nproc) intl \
	&& pecl install redis \
	&& docker-php-ext-enable redis \
	&& pecl install igbinary \
	&& docker-php-ext-enable igbinary \
	&& pecl install xdebug \
	&& apt-get remove -y \
		libicu-dev \
		libzip-dev

COPY . /workdir
COPY ./infra/entrypoint.sh /docker-entrypoint.sh

RUN chmod u+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 80
EXPOSE 6000
EXPOSE 6001

```

Entrypoint:

```
#!/usr/bin/env bash
set -e

export APP_ENV=$1
export PROJECT_DIR=/workdir
export INFRA_DIR=${PROJECT_DIR}/infra

echo Initializing ${APP_ENV} mode
echo PHP ini dir ${PHP_INI_DIR}
echo Project dir ${PROJECT_DIR}
echo Image tag $(cat .image-tag)

rm -f ${PHP_INI_DIR}/conf.d/php.stderr-log.ini
rm -f ${PHP_INI_DIR}/conf.d/php.xdebug.ini

if [[ ${APP_ENV} = 'dev' ]]; then
    # Local development in local container
    cp ${PHP_INI_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini
    cp ${INFRA_DIR}/php.stderr-log.ini ${PHP_INI_DIR}/conf.d/php.stderr-log.ini
    cp ${INFRA_DIR}/php.xdebug.ini ${PHP_INI_DIR}/conf.d/php.xdebug.ini
	echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> ${PHP_INI_DIR}/conf.d/php.xdebug.ini
	RR_NUM_WORKERS=1
elif [[ ${APP_ENV} = 'staging' ]]; then
    # Staging
    cp ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini
    cp ${INFRA_DIR}/php.stderr-log.ini ${PHP_INI_DIR}/conf.d/php.stderr-log.ini
	RR_NUM_WORKERS=1
elif [[ ${APP_ENV} == 'prod' ]]; then
    # Production
    cp ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini
    cp ${INFRA_DIR}/php.stderr-log.ini ${PHP_INI_DIR}/conf.d/php.stderr-log.ini
	RR_NUM_WORKERS=10
else
    echo Unknown container configuration ${APP_ENV}
    exit 1
fi

echo Running app in ${APP_ENV} mode


rr serve -v -d -w ${PROJECT_DIR}/public -c ${INFRA_DIR}/rr.yml -o http.workers.command="php ${PROJECT_DIR}/src/rr-bootstrap.php" -o http.workers.pool.numWorkers=${RR_NUM_WORKERS} -o http.address="0.0.0.0:80" -l plain
```

```
docker-compose:
version: "3.7"
services:
  php:
    image: custom-php:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    ports:
      - "80:80"
      - "6000:6000"
      - "6001:6001"
    command: "dev"
    environment:
      PHP_IDE_CONFIG: serverName=imhome-docker.loc
    volumes:
      - type: bind
        source: /host_mnt/c/path-to-the-project-under-windows
        target: /workdir

networks:
  webnet:
```

Run command:
```
docker stack deploy -c ./infra/docker-compose.yml test
```

**Comment by wolfy-j** [comment]
Can you show me your `.rr` file? You are using default RPC configuration, correct?

**Comment by speller** [comment]
Here is my rr.yml:

```
http:
  address: 0.0.0.0:81 # Local dev value. Overwritten to 80 in the entrypoint.sh to work inside a container
  workers:
    pool:
      numWorkers: 1 # Local dev value. Overwritten in the entrypoint.sh for containerized mode
      # maximum jobs per worker, 0 - unlimited.
      maxJobs:  10000
      # for how long worker is allowed to be bootstrapped.
      allocateTimeout: 60
      # amount of time given to worker to gracefully destruct itself.
      destroyTimeout:  60
    relay:    "pipes"

  # max POST request size, including file uploads in MB.
  maxRequest: 50

# static file serving. remove this section to disable static file serving.
static:
  # root directory for static file (http would not serve .php and .htaccess files).
  dir:   "."

  # list of extensions for forbid for serving.
  forbid: [".php", ".htaccess"]

  always: [".ico", ".html", ".css", ".js"] 
```
