### ISSUE TITLE
rpc unix socket is not closed sometimes

### ISSUE THREAD

**Issue by Richard87** [spiral/roadrunner#19]
There is some issues with the shutdown procedures, when using either STDOUT/IN or Unix socket it doesn't close it, and then it can't start properly later (I havent tried a TCP socket yet).

```
./rr serve -v -d
DEBU[0000] [rpc]: started                               
DEBU[0000] [http]: started                              
DEBU[0000] [static]: started                            
ERRO[0000] [rpc]: listen unix ./var/roadrunner2.sock: bind: address already in use 
DEBU[0000] [http]: stopped                              
ERRO[0000] [http]: listen unix ./var/roadrunner2.sock: bind: address already in use 
^C%                                                                                   
```

**Comment by wolfy-j** [comment]
Can you post your .rr file here?

**Comment by Richard87** [comment]
Hi!

some changes (I was slightly confused by the different listen directives for rpc and listen...:

```
# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server
  enable: true

  # rpc connection DSN. Supported TCP and Unix sockets.
  # listen: tcp://127.0.0.1:6001
  listen: unix://./var/roadrunner3.sock

# http service configuration.
http:
  # set to false to disable http server.
  enable:     true

  # http host to listen.
  address:    0.0.0.0:8000

  # max POST request size, including file uploads in MB.
  maxRequest: 200

  # file upload configuration.
  uploads:
    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # http worker pool configuration.
  workers:
    # php worker command.
    command:  "php psr-worker.php"

    # connection method (pipes, tcp://:9000, unix://socket.unix).
    relay:    "pipes"

    # worker pool configuration.
    pool:
      # number of workers to be serving.
      numWorkers: 4

      # maximum jobs per worker, 0 - unlimited.
      maxJobs:  0

      # for how long pool should attempt to allocate free worker (request timeout). Nanoseconds atm. (60s)
      allocateTimeout: 60000000000

      # amount of time given to worker to gracefully destruct itself. Nanoseconds atm. (30s)
      destroyTimeout:  30000000000

# static file serving.
static:
  # serve http static files
  enable:  true

  # root directory for static file (http would not serve .php and .htaccess files).
  dir:   "web"

  # list of extensions to forbid for serving.
  forbid: [".php", ".htaccess", "package.json", "yarn.lock"]
```

(Also, executing `./rr http:workers` never completes, I have a feeling it's related ;) )
