### ISSUE TITLE
Graceful shutdown doesn't work if metrics or health service is enabled

### ISSUE THREAD

**Issue by sixdayz** [spiral/roadrunner#197]
It works for this config:

```
static:
  dir: "../public"
  forbid: [".php", ".htaccess"]
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001
http:
  address: 0.0.0.0:80
  workers:
    command: "php ../roadrunner/worker.php"
    relay: "tcp://127.0.0.1:10000"
```

But it doesn't work when I set up another config:

```
static:
  dir: "../public"
  forbid: [".php", ".htaccess"]
health:
  address: 127.0.0.1:2114
metrics:
  address: 0.0.0.0:2112
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001
http:
  address: 0.0.0.0:80
  workers:
    command: "php ../roadrunner/worker.php"
    relay: "tcp://127.0.0.1:10000"
```

I tried to remove `health` and `metrics` separately. It didn't help. Graceful shutdown doesn't work with any of these sections enabled.
