### ISSUE TITLE
File watcher module with auto-reload capabilities

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#249]
RR module which will auto-reload worker in case of FS changes.
Linked issue: #102

**Comment by wolfy-j** [comment]
- list of directories and file extwnsion

```yaml
reload:
  include:       ["app/src", "vendor"]
  extensions:  [".php", ".dark.php"]
  services:      ["http", "grpc", "jobs"]
```
