### ISSUE TITLE
How to run the workers as non root (or any) user ?

### ISSUE THREAD

**Issue by adhocore** [spiral/roadrunner#290]
Mainly useful for dockerized app but should be added advantage elsewhere as well.

```yaml
http:
  address:         0.0.0.0:8080
  workers.command: "php worker.php"
```

what i am looking for is `workers.user: %user%`
and not `  workers.command: "su %user%  -c 'php worker.php'"`

---

Finally, thanks for roadrunner 🥇
