### ISSUE TITLE
gzip not working

### ISSUE THREAD

**Issue by Alexfilus** [spiral/roadrunner#312]
Hi. GZIP compression not working. 
My config:
```
http:
  address: 0.0.0.0:4000
  workers:
    command:         "php app.php"
    pool.numWorkers: 1
    pool.maxJobs:    1
  gzip:
    enable: true
gzip:
  enable: true
# queue and jobs
jobs:
  dispatch:
    app-job-*.pipeline: "local"
  pipelines:
    local:
      broker: "ephemeral"
  consume: ["local"]

  workers:
    command: "php app.php"
    pool.numWorkers: 2

# serve static files
static:
  dir:    "public"
  forbid: [".php", ".htaccess"]

metrics:
  # prometheus client address (path /metrics added automatically)
  address: localhost:2112

# control the max memory usage
limit:
  services:
    http.maxMemory: 100
    jobs.maxMemory: 100

# reload can reset rr servers when files change
reload:
  # refresh interval (default 1s)
  interval: 1s

  # file extensions to watch, defaults to [.php]
  patterns: [".php"]

  # list of services to watch
  services:
    http:
      # list of dirs, "" root
      dirs: [""]

      # include sub directories
      recursive: true
```
