### ISSUE TITLE
[BUG] http:reset seems not working

### ISSUE THREAD

**Issue by ghost** [spiral/roadrunner#314]
roadrunner 1.7.1

background:
1, laravel 7.8.1 with https://github.com/avto-dev/roadrunner-laravel integration
2, roadrunner rpc enabled.
3, 
opcache.enable => On => On
opcache.enable_cli => Off => Off
4, systemd unit file
```
[Unit]
Description=High-performance PHP application server

[Service]
Type=simple
ExecStart=/usr/local/bin/rr serve -c /xxx/.rr.yaml
ExecReload=/usr/local/bin/rr http:reset -c /xxx/.rr.yaml
Restart=always
RestartSec=30
User=www-data
[Install]
WantedBy=default.target
```
4, systemctl reload rr.service,  success
5, ./rr  -c .rr.yaml http:workers. all workers are "created x seconds ago"
6, new code doesn't work.
~~7, systemctl restart rr.service, new code works~~
7, stop first and and re-serve to make new code works
`/usr/local/bin/rr stop -c /xxx/.rr.yaml; /usr/local/bin/rr serve -c /xxx/.rr.yaml `

Please let me know if you need anything else.

**Comment by wppd** [comment]
here is my rr.yaml
```
rpc:
  enable: true
  listen: tcp://127.0.0.1:18081
gzip:
  enable: true
reload:
  enable: false
http:
  address:   0.0.0.0:8081
  # in MB
  maxRequestSize: 5000
  uploads:
    forbid: [".php", ".exe", ".bat"]
  workers:
    command:  "php ./vendor/bin/rr-worker"
    pool:
      #it'll use the number of cpu processors
      #numWorkers: 4
      maxJobs:  10
      allocateTimeout: 60
      destroyTimeout:  60

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]

limit:
  # check worker state each second
  interval: 2

  # custom watch configuration for each service
  services:
    # monitor http workers
    http:
      # maximum allowed memory consumption per worker (soft)
      maxMemory: 1024

      # maximum time to live for the worker (soft)
      TTL: 0

      # maximum allowed amount of time worker can spend in idle before being removed (for weak db connections, soft)
      idleTTL: 0

      # max_execution_time (brutal)
      execTTL: 300

```
when reload: true, its working as expected, no need to call http:reset. I don't really want to use reload in production. thanks
