### ISSUE TITLE
[BUG] Worker user permissions issue

### ISSUE THREAD

**Issue by mqwerty** [spiral/roadrunner#332]
I send file using POST request to the server.

```js
const formData = new FormData();
formData.append('file', this.file);
http
  .post('upload', formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  })
  .then(response => {
    console.log(response)
  })
  .catch(error => {
    console.error(error)
  })
```

Getting error:
```
fopen(/tmp/upload000932162): failed to open stream: Permission denied in /app/vendor/spiral/roadrunner/src/Diactoros/StreamFactory.php:41
```

Trace
```
Whoops\Exception\ErrorException: fopen(/tmp/upload192874436): failed to open stream: Permission denied in /app/vendor/spiral/roadrunner/src/Diactoros/StreamFactory.php:41
Stack trace:
#0 [internal function]: Whoops\Run->handleError()
#1 /app/vendor/spiral/roadrunner/src/Diactoros/StreamFactory.php(41): fopen()
#2 /app/vendor/spiral/roadrunner/src/PSR7Client.php(179): Spiral\RoadRunner\Diactoros\StreamFactory->createStreamFromFile()
#3 /app/vendor/spiral/roadrunner/src/PSR7Client.php(93): Spiral\RoadRunner\PSR7Client->wrapUploads()
#4 /app/src/Router.php(88): Spiral\RoadRunner\PSR7Client->acceptRequest()
#5 /app/src/App.php(32): App\Router::handle()
#6 /app/index.php(6): App\App->run()
#7 {main}
```

Permissions for /tmp directory - 1777

The version of RR used: 1.8.1

PHP 7.4.6, Alpine Linux v3.11

**Comment by 48d90782** [comment]
@mqwerty Did you use "worker.user" option in .rr.yaml?

**Comment by mqwerty** [comment]
> @mqwerty Did you use "worker.user" option in .rr.yaml?

Yes.

Config:
```
http:
  address: :80
  workers:
    user: "app"
    command: "php /app/index.php"
    pool:
      numWorkers: 1

static:
  dir:   "/app/public"
  forbid: [".php", ".htaccess"]

headers:
  cors:
    allowedOrigin: "http://localhost:8080"
    allowedHeaders: "Accept, Accept-Language, Content-Language, Content-Type, Cache-Control, Cookie, Csrf, X-Requested-With"
    allowedMethods: "GET,POST,PUT,DELETE"
    allowCredentials: true
    exposedHeaders: "Content-Language, Content-Length, Content-Type, Cache-Control, Expires, Last-Modified, Pragma, Set-Cookie"
    maxAge: 3600
  response:
    "X-Frame-Options": "deny"
    "X-Content-Type-Options": "nosniff"
    "X-XSS-Protection": "1; mode=block"
    "Referrer-Policy": "no-referrer-when-downgrade"

rpc:
  enable: true
  listen: tcp://:6001

health:
  address: :2113

limit:
  interval: 1
  services:
    http:
      maxMemory: 100
      TTL: 0
      idleTTL: 0
      execTTL: 60

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      dirs: ["/app"]
      recursive: true
```
