### ISSUE TITLE
Adding headers to static files

### ISSUE THREAD

**Issue by maxbaldanza** [spiral/roadrunner#336]
We are using roadrunner with PHP and docker and have the following `.rr.yaml`:

```yaml
http:
  address: :8080
  workers:
    command: "php /var/www/app/worker.php"
    pool:
      numWorkers: 4

# Additional HTTP headers and CORS control.
headers:
  # Middleware to handle CORS requests, https://www.w3.org/TR/cors/
  cors:
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
    allowedOrigin: "*"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
    allowedHeaders: "*"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods
    allowedMethods: "GET,POST,PUT,DELETE"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
    allowCredentials: true

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
    exposedHeaders: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"

    # Max allowed age in seconds
    maxAge: 600

  # Automatically add headers to every request passed to PHP.
  request:
    "Example-Request-Header": "Value"

  # Automatically add headers to every response.
  response:
    "X-Powered-By": "RoadRunner"

# static file serving. remove this section to disable static file serving.
static:
  # root directory for static file (HTTP would not serve .php and .htaccess files).
  dir:   "/var/www/app/public"

  # list of extensions for forbid for serving.
  forbid: [".php", ".htaccess"]

```

This adds the headers to PHP requests but for static files the headers aren't added. Is there a way to do this?
