### ISSUE TITLE
[BUG] golang "invalid memory address or nil pointer dereference" error

### ISSUE THREAD

**Issue by vvval** [spiral/roadrunner#341]
Unfortunately, I can't provide any details on that, bc roadrunner crashes every now and then based on incorrect PHP worker (yes, they're always present some app PHP error for these cases). It's run under docker container and `serve` command is an entry command

```DEBU[0000] [metrics]: started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x92f9de]

goroutine 34 [running]:
github.com/spiral/roadrunner.(*StaticPool).Workers(0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/spiral/roadrunner@v1.8.0/static_pool.go:110 +0x4e
github.com/spiral/roadrunner.(*Server).Workers(0xc0002a0fc0, 0x0, 0x0, 0x14dc050)
        /go/pkg/mod/github.com/spiral/roadrunner@v1.8.0/server.go:217 +0x44
github.com/spiral/roadrunner/util.ServerState(0xc0002a0fc0, 0xc0002a0fc0, 0xdc0660, 0xc000056fb8, 0xa4ce99, 0xc0002970e0)
        /go/pkg/mod/github.com/spiral/roadrunner@v1.8.0/util/state.go:52 +0x73
github.com/spiral/roadrunner/cmd/rr/http.(*metricCollector).collectMemory(0xc0002ae580, 0xc0000e0bb0, 0x2540be400)
        /go/pkg/mod/github.com/spiral/roadrunner@v1.8.0/cmd/rr/http/metrics.go:112 +0xb8
created by github.com/spiral/roadrunner/cmd/rr/http.init.1.func1
        /go/pkg/mod/github.com/spiral/roadrunner@v1.8.0/cmd/rr/http/metrics.go:35 +0x286```

**Comment by jimu-liubin** [comment]
+1

**Comment by rauanmayemir** [comment]
Confirming this to be the case.
For me, this happens during the pod startup. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x91eefb]

goroutine 32 [running]:
github.com/spiral/roadrunner.(*StaticPool).Workers(0x0, 0x0, 0x0, 0x0)
	github.com/spiral/roadrunner@v1.8.0/static_pool.go:110 +0x5b
github.com/spiral/roadrunner.(*Server).Workers(0xc0003022a0, 0x0, 0x0, 0x16eea10)
	github.com/spiral/roadrunner@v1.8.0/server.go:217 +0x44
github.com/spiral/roadrunner/util.ServerState(0xc0003022a0, 0xc0003022a0, 0xebf998, 0xc00006e7b8, 0xb160c9, 0xc0001e2c60)
	github.com/spiral/roadrunner@v1.8.0/util/state.go:52 +0x73
github.com/spiral/roadrunner/cmd/rr/http.(*metricCollector).collectMemory(0xc0001ed720, 0xc0001ae000, 0x2540be400)
	github.com/spiral/roadrunner@v1.8.0/cmd/rr/http/metrics.go:112 +0xb8
created by github.com/spiral/roadrunner/cmd/rr/http.init.1.func1
	github.com/spiral/roadrunner@v1.8.0/cmd/rr/http/metrics.go:35 +0x286
```

It didn't really bother me as supervisord just kept retrying until it worked fine and I discovered this only accidentally in the log.

My docker container is based on fresh-ish debian buster and spiral binary version 2.4.18. Here's the RR config I'm using:

```
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001

metrics:
  address: localhost:2112

http:
  address: 0.0.0.0:30080

  # HTTP service provides HTTP2 transport
  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128

  maxRequestSize: 64

  uploads:
    forbid: [".php", ".exe", ".bat"]

  # cidr blocks which can set ip using X-Real-Ip or X-Forwarded-For
  trustedSubnets: ["10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]

  # http worker pool configuration.
  workers:
    command: "php app.php"

    # connection method (pipes, tcp://:9000, unix://socket.unix). default "pipes"
#    relay: "pipes"
    relay: "unix://socket.unix"

    pool:
      # number of workers to be serving.
      numWorkers: 8

      # maximum jobs per worker, 0 - unlimited.
      maxJobs:  500

      # for how long worker is allowed to be bootstrapped.
      allocateTimeout: 300

      # amount of time given to the worker to gracefully destruct itself.
      destroyTimeout:  300
```

**Comment by 48d90782** [comment]
Thanks, @rauanmayemir @vvval , I'll take a look.

**Comment by Shikachuu** [comment]
Hey,
I might run into the same isssue as the others above me,
```sh
./rr serve -v -d  
DEBU[0000] [static]: disabled                           
DEBU[0000] [rpc]: started                               
DEBU[0000] [http]: started                              
DEBU[0000] [metrics]: started                           
DEBU[0000] [health]: started                            
DEBU[0000] [reload]: started                            
ERRO[0000] [http]: [http]: process error: fork/exec : no such file or directory 
DEBU[0000] [rpc]: stopped                               
DEBU[0000] [metrics]: stopped                           
DEBU[0000] [health]: stopped                            
DEBU[0000] [reload]: stopped                            
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x915c3b]

goroutine 26 [running]:
github.com/spiral/roadrunner.(*StaticPool).Workers(0x0, 0x0, 0x0, 0x0)
        github.com/spiral/roadrunner/static_pool.go:110 +0x5b
github.com/spiral/roadrunner.(*Server).Workers(0xc0001da5b0, 0x0, 0x0, 0x1178790)
        github.com/spiral/roadrunner/server.go:217 +0x44
github.com/spiral/roadrunner/util.ServerState(0xc0001da5b0, 0xc0001da5b0, 0xbb84a8, 0xc00004c7b8, 0xa07509, 0xc0002953e0)
        github.com/spiral/roadrunner/util/state.go:52 +0x73
github.com/spiral/roadrunner/cmd/rr/http.(*metricCollector).collectMemory(0xc0002a2760, 0xc0000ec000, 0x2540be400)
        github.com/spiral/roadrunner/cmd/rr/http/metrics.go:112 +0xb8
created by github.com/spiral/roadrunner/cmd/rr/http.init.1.func1
        github.com/spiral/roadrunner/cmd/rr/http/metrics.go:35 +0x286
```

Weird fact, this panic only appears 3 starts from 5 , at least for me.
`process error: fork/exec : no such file or directory ` <- this appears every single time, don't mind it, it was just a typo, I fixed it since.
.rr.yaml:
```yaml
metrics:
  address: localhost:2112

rpc:
  listen: tcp://:6001

http:
  address: 0.0.0.0:8080
  workers:
    command: "php index.php"
    pool:
      maxJobs: 5
      allocateTimeout: 100
      destroyTimeout: 100
      numWorkers: 4

maxRequestSize: 64

uploads:
  forbid: [".php", ".exe", ".bat", ".sh"]

limit:
  interval: 5
  services:
    http:
      maxMemory: 100
      TTL: 0
      idleTTL: 50

health:
  address: localhost:2113

reload:
  enabled: true
  interval: 1s
  patterns: [".php"]
  services:
    http:
      recursive: true
      ignore: ["vendor"]
      dirs: ["."]
      patterns: [".php", ".go", ".md"]
```
