### ISSUE TITLE
[BUG] Sometimes the file watcher stops working

### ISSUE THREAD

**Issue by siamskoi** [spiral/roadrunner#362]
My config rr.yaml
```
# http service configuration.
# Example: https://roadrunner.dev/docs/intro-config
http:
    address: 0.0.0.0:8117

    workers:
        command: "php /var/www/app/psr-worker.php"
        pool:
            numWorkers: 4
            maxJobs:    0

# Additional HTTP headers and CORS control.
headers:
    cors:
        allowedOrigin: "*"
        allowedHeaders: "*"
        allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"

# control the max memory usage
limit:
    services:
        http.maxMemory: 100
        jobs.maxMemory: 100

env:
    LIFERELOAD: true

reload:
    # enable or disable file watcher
    enabled: true
    interval: 1s
    patterns: [".php"]
    services:
        http:
            recursive: true
            ignore: ["vendor"]
            patterns: [".php", ".go", ".md",]
            dirs:     ["/var/www/app/src"]
```

I edit some files, and see: 
```
DEBU[0277] new worker pool                     
DEBU[0277] [http] found 1 file(s) changes, reloading
```

It's ok. But, sometimes file watcher stops working. And I must restart RR, or wait 5 minutes and more.
~100 files in catalog /var/www/app/src

</p>
</details>
