### ISSUE TITLE
Please, make builds with turned off pprof

### ISSUE THREAD

**Issue by broken-ufa** [spiral/roadrunner#366]
When I trying to run 2 instances or roadrunner, I got an error:
**listen tcp :6061: bind: address already in use**
and I can't found any arguments to turn off pprof.

Please, make builds with turned off pprof also in releases.

(I'm not familiar with golang)

**Comment by 48d90782** [comment]
@broken-ufa oh... let me check

**Comment by 48d90782** [comment]
@broken-ufa I guess that you use a command like: `./rr serve -d ...`. In this case `-d` is the debug mode. Just you RR without this option.

**Comment by 48d90782** [comment]
@wolfy-j 6061 is a hardcoded port for the standard golang pprof endpoint. It is active only in the Debug mode.

**Comment by broken-ufa** [comment]
Oh yes, thank you!
port 6061 opened because I use flag -d
It not RPC port (see https://github.com/spiral/roadrunner/pull/248#issuecomment-586863008)

**Comment by wolfy-j** [comment]
O__o

Then it conflicts with the default RPC port:

```yaml
# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server
  enable: true

  # rpc connection DSN. Supported TCP and Unix sockets.
  listen:     tcp://127.0.0.1:6001
```
