### ISSUE TITLE
[BUG] Malformed worker response

### ISSUE THREAD

**Issue by themaiby** [spiral/roadrunner#395]
```php
    public function index(Request $request)
    {
        return User::paginate();
    }
```
RR launched in docker.

I expected to see paginated result on my index route, instead RR shows error: **malformed worker response**.

**Console output:**
```bash
INFO[0002] 172.18.0.1 {20.7ms} 500 GET http://localhost:5000/api/management/users malformed worker response 
```

The version of RR used: *1.8*
As worker used: https://github.com/spiral/roadrunner-laravel
Laravel version: 8.14

In **laravel telescope** I can see 200 OK response with all data, in Postman I see only this RR error.

**.rr.yml**
```yml
rpc:
  enable: true
  listen:     tcp://127.0.0.1:6001

metrics:
  address: localhost:2112
  collect:
    app_metric:
      type:    histogram
      help:    "Custom application metric"
      labels:  ["type"]
      buckets: [0.1, 0.2, 0.3, 1.0]

http:
  address: 0.0.0.0:5000

  fcgi:
    address: tcp://0.0.0.0:6920

  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128

  maxRequestSize: 200

  uploads:
    forbid: [".php", ".exe", ".bat"]

  trustedSubnets: ["10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "172.16.0.0/12", "172.18.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]

  workers:
    command: 'php ./vendor/bin/rr-worker'
    relay:    "pipes"
    user: ""

    pool:
      numWorkers: 4
      maxJobs:  0
      allocateTimeout: 60
      destroyTimeout:  60

limit:
  interval: 1
  services:
    http:
      maxMemory: 100
      TTL: 0
      idleTTL: 0
      execTTL: 60

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]

health:
  address: localhost:2113

reload:
  interval: 1s
  patterns: [".php"]

  services:
    http:
      dirs: [""]
      recursive: true
```

</p>
</details>

Any idea what this might be related to?
Thanks.
