### ISSUE TITLE
[RR2] Update `Jobs` plugin

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner#403]
1. Update Jobs plugin to the actual RR version
2. More description in the related PR.

All information about implementation, features, load testing can be found in the attached PR.

**Comment by rustatian** [comment]
```yaml
jobs:
  # worker pool configuration
  pool:
    num_workers: 4

  # list of broker pipelines associated with endpoints
  pipelines:
    test-local:
      driver: ephemeral
      queue: defaultA
      priority: 10

    test-1: # pipeline name
      driver: amqp # nats, beanstalk --- local and global configuration like in the broadcast
      queue:  default # amqp mandatory option
      priority: 2

    test-2:
      driver: beanstalk
      tube:   default
      priority: 1

    test-3:
      driver: sqs
      queue:  default
      declare:
        MessageRetentionPeriod: 86400


  # list of pipelines to be consumed by the server, keep empty if you want to start consuming manually
  consume: ["test-local", "test-1"]

----------------------------------- GLOBAL -----------------------------------

 # rabbitmq and similar servers
  amqp:
    addr:     amqp://guest:guest@localhost:5672/

  # beanstalk configuration
  beanstalk:
    addr:    tcp://localhost:11300

  # amazon sqs configuration
  sqs:
    key:      api-key
    secret:   api-secret
    region:   us-west-1
    endpoint: http://localhost:9324
```

All arch diagrams are currently in ALPHA.

`RCP PUSH` diagram:   
![image](https://user-images.githubusercontent.com/8040338/122187822-12299d00-ce98-11eb-937b-b48882fdaac2.png)

`Import scheme`   
![image](https://user-images.githubusercontent.com/8040338/124586192-d4001780-de5e-11eb-8b18-a0bddc7ff85d.png)

`Root plugin serve`   
![image](https://user-images.githubusercontent.com/8040338/124586145-c5b1fb80-de5e-11eb-9971-73b6a5602df9.png)

`Driver`   
![image](https://user-images.githubusercontent.com/8040338/124586227-de221600-de5e-11eb-91bd-c8c632c3186d.png)

`Proto`
```protobuf
syntax = "proto3";

package jobs.v1beta;
option go_package = "./;jobsv1beta";

// single job request
message Request {
    Job job = 1;
}

// batch jobs request
message BatchRequest {
    repeated Job jobs = 1;
}

// RPC response
message Response {
    string id = 1;
}

message Job {
    string job = 1;
    string payload = 2;
    Options options = 3;
}

message Options {
    uint64 priority = 1;
    string id = 2;
    string pipeline = 3;
    uint64 delay = 4;
    uint64 attempts = 5;
    uint64 retry_delay = 6;
    uint64 timeout = 7;
}
```
