### ISSUE TITLE
[RR2] Add global ENV variables for server.Cmd

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#466]
Need 2 default env variables set for every process:

RR_RPC = address of RPC service listener
RR_RELAY = communication relay (pipes, tcp://...)

**Comment by wolfy-j** [comment]
Also RR_CONFIG = JSON(full config)

**Comment by wolfy-j** [comment]
This issue is a high priority due to non-compatibility with RR 1.0.

**Comment by 48d90782** [comment]
RR 2 is not-compatible with RR 1. You can use `env` variables directly in the `server`:
```yaml
server:
  command: "php tests/psr-worker-bench.php"
  user: ""
  group: ""
  env:
    "RR_HTTP": "true"
    "RR_RPC": "tcp://127.0.0.1:6001"
  relay: "pipes"
  relayTimeout: "20s"
  ```
`RR_RELAY` can be deduced from its internal parameters (`relay` key), and then it can be set automatically. Other env variables should not be hidden and should be set via the `env` key in the `server` explicitly (from my POV).
