### ISSUE TITLE
[RR2] Command limitation

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#511]
It is impossible to run RR2 with a custom path to PHP executable (which was possible in RR1).

I tried this code:

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "c:\\php-8\\php.exe worker.php"

temporal:
  address: "localhost:7233"
  activities:
    num_workers: 10

logs:
  level: debug
  channels:
    temporal:
      level: fatal
```

I expected to see this happen:
RR should use given PHP path.

Instead, this happened: 
RR failed with:
```
server_plugin_cmd_factory: first arg in command should be `php`
```

The version of RR used: v2.0.0-beta9

Errortrace, Backtrace or Panictrace
```
2021/01/29 13:46:02 handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex workflow.Plugin, stopping execution, error: workflow_plugin_serve:
        workflow_plugin_start_pool:
        new_workflow_pool:
        server_plugin_new_worker:
        server_plugin_cmd_factory: first arg in command should be `php`
```
