### ISSUE TITLE
[RR2] Broadcast and broadcast-ws plugins migrate

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#513]
Migrate the following plugins to the RR2:
1. https://github.com/spiral/broadcast
2. https://github.com/spiral/broadcast-ws
3. Have a look to the following issue: https://github.com/spiral/broadcast-ws/issues/2

**Comment by 48d90782** [comment]
Config section for the `ws` and broadcast plugin at all won't change hugely, and only new drivers are going to be added:
```yaml
broadcast:
  # path to enable web-socket handler middleware
  path: /ws

  # optional, redis broker configuration
  redis:
    addrs:
      - "localhost:6379"
      # if a MasterName is passed a sentinel-backed FailoverClient will be returned
    master_name: ""
    username: ""
    password: ""
    db: 0
    sentinel_password: ""
    route_by_latency: false
    route_randomly: false
    dial_timeout: 0 # accepted values [1s, 5m, 3h]
    max_retries: 1
    min_retry_backoff: 0 # accepted values [1s, 5m, 3h]
    max_retry_backoff: 0 # accepted values [1s, 5m, 3h]
    pool_size: 0
    min_idle_conns: 0
    max_conn_age: 0 # accepted values [1s, 5m, 3h]
    read_timeout: 0 # accepted values [1s, 5m, 3h]
    write_timeout: 0 # accepted values [1s, 5m, 3h]
    pool_timeout: 0 # accepted values [1s, 5m, 3h]
    idle_timeout: 0 # accepted values [1s, 5m, 3h]
    idle_check_freq: 0 # accepted values [1s, 5m, 3h]
    read_only: false
```
Except for `redis`, other NoSQL storages will be supported, such as `in-memory` (and others in the future).

**Comment by 48d90782** [comment]
After discussion with @wolfy-j, we decided to update the `broadcast` configuration to the following:
```yaml
broadcast:
  ws-us-region-1:
    subscriber: ws
      path: "/ws"
      ... other subscriber specific options

    driver: redis
    address:
      - 6379
    db: 0
    .. other driver specific options
```

`ws-us-region-1` - generic (user-defined) name for the section. It might have any name.
Subscriber is the object which subscribes to the events with the provided topic, topics, or patterns. 
Driver for the subscriber is the storage for topics, patterns, and associated messages from the publisher.
The publisher is the PHP worker who can publish messages with the defined topic, topics, or patterns.
