### ISSUE TITLE
[BUG] why the builded binary can not run directly?

### ISSUE THREAD

**Issue by beanhacker** [spiral/roadrunner#534]
run: 
     rr.exe serve
    use config i copyed(.rr.yaml):
          http: address: 0.0.0.0:8080
          workers.command: "php worker.php"

error: 
2021/02/07 14:24:48 handle_serve_command: Init error:
        endure_initialize:
        endure_add_edges:
        endure_add_init_deps:
        endure_add_interface_dep: can't find dependency: logger.Logger for the vertex: memcached.Plugin

suggest:
     i have try this ispired package for a period of time, no one successed. can you build one exe with a ready config to run directly when download your binary? go's spirit is simple and simple, but yours not imple this.

thanks.

**Comment by 48d90782** [comment]
Hey @beanhacker. Nice to meet you. Thanks for the report and sorry for the bad UX. At the moment RR2 in the beta stage, so, there are expected to be some bugs inside :)
If I understood correctly, you tried to run RR2 with the following configuration:
```yaml
http:
    address: 0.0.0.0:8080
    
workers.command: "php worker.php"
```
You have to rewrite this config to be compatible with RR2:
```yaml
http:
    address: 0.0.0.0:8080
server:
    command: "php worker.php"
logs:
    level: [debug,info,warning,panic] <---- choose the level you need
```

I found a bug in the endure interfaces resolving mechanism. And that's why you get this error:
`endure_add_interface_dep: can't find dependency: logger.Logger for the vertex: memcached.Plugin`
Also, `logs` is a mandatory field in the `.rr.yaml` RR2 config. We will definitely cover this in the documentation. Please, stay tuned and wait for the next beta release.
