### ISSUE TITLE
[BUG, RR2] Static does not work

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#556]
I tried this code:

```yaml
rpc:
   listen: tcp://127.0.0.1:6001

server:
   command: "php worker.php"
   relay: "pipes"
   env:
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: "\"mode=debug\""

http:
   address: "0.0.0.0:8080"
   middleware: [ "static" ]
   pool:
      num_workers: 1
      debug: true
   static:
      dir: "public/"

logs:
   level: debug

```

I expected to see this happen: serve file via `localhost:8080/hello.txt` where hello.txt located in public dir.

Instead, this happened: requested falled back to PHP script.

The version of RR used: v2.0.0-RC2
