### ISSUE TITLE
[RR2, HTTP] Update redirect flags to the config

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#583]
If HTTP plugin uses `ssl` with `redirect` key set to the `true` RR return code would be `307 Temporary Redirect`. On the other hand, a user might need the `308 Permanent Redirect` response but have no ability to configure that.
1. Add `permanent` flag to the `http.ssl` config section with the bool values.
```yaml
  ssl:
    # host and port separated by semicolon (default :443)
    address: :8892
    redirect: false
    permanent: true # or false
    cert: fixtures/server.crt
    key: fixtures/server.key
    root_ca: root.crt
```
2. If `permanent` is set to `true` user the `308 Permanent Redirect`, otherwise use `307 Temporary Redirect`.
3. The default value for the key should be false (current behavior).
4. Invocation happens here: https://github.com/spiral/roadrunner/blob/master/plugins/http/plugin.go#L286.
