### ISSUE TITLE
[Documentation] Autoreload configuration example possibly out of date

### ISSUE THREAD

**Issue by jwillp** [spiral/roadrunner#586]
The documentation for auto-reloading at <https://roadrunner.dev/docs/beep-beep-reload>
displays the following configuration:

```
reload:
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [ ".php" ]
  # list of included for sync services
  plugins:
    http:
      # recursive search for file patterns to add
      recursive: true
      # ignored folders
      ignore: [ "vendor" ]
      # service specific file pattens to sync
      patterns: [ ".php", ".go", ".md" ]
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs: [ "." ]
```

However, I could not get it to work this way. Looking at the tests [here](https://github.com/spiral/roadrunner/blob/b9c9909b98c1b3e15421a4bcad9e8fcc01332d37/tests/plugins/reload/configs/.rr-reload.yaml) I saw that instead of the `plugins` key the `services` key was used.

Doing this change solved the issue.

Is it possible that the documentation is out of date for this?

Tried looking at [this file](https://github.com/spiral/roadrunner/blob/b9c9909b98c1b3e15421a4bcad9e8fcc01332d37/plugins/reload/plugin.go) but could not see any reference to the `plugins` key only the `services` key.
