### ISSUE TITLE
[RR2, SSL] Root CA (in config) should be optional

### ISSUE THREAD

**Issue by tarampampam** [spiral/roadrunner#587]
Right now, without Root CA defining SSL will not works:

```yaml
http:
  ssl:
    address: 0.0.0.0:443
    redirect: true
    cert: /ssl-cert/self-signed.crt
    key: /ssl-cert/self-signed.key
    #root_ca: /etc/ssl/certs/ca-certificates.crt
```

https://github.com/spiral/roadrunner/blob/8f6cafdc0948a5ea13bf9a811b576aa4b3ef7e4a/plugins/http/config/http.go#L55-L57

Maybe we can make Root CA optional?
