### ISSUE TITLE
[BUG, RR2] listen tcp :6061: bind: address already in use

### ISSUE THREAD

**Issue by Smolevich** [spiral/roadrunner#606]
I tried run roadrunner with config :

```yaml
server:
  command: "php rr.php"
  env:
    XDEBUG_SESSION: 1
http:
  address: :8080
  workers:
    pool:
      numWorkers: 4
      maxJobs:  1000

static:
  dir:   "html"
  forbid: [".php", ".htaccess"]

metrics:
  address: :2112

health:
  address: :2114

reload:
  # enable or disable file watcher
  enabled: true
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [ ".php" ]

```
and server failed with error `2021/03/19 08:43:18 listen tcp :6061: bind: address already in use`
I expected to see this happen: *successful run server*

Instead, this happened: *server failed*

The version of RR used: *2.0.1*

**Comment by 48d90782** [comment]
Hey @Smolevich , few corrections for the config:
1. `health` -> `status` https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L412
2. Do not use flag `-d` with the RR2, now all logs related stuff (debug logs, etc lays in the `logs` config section). https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L55
3. `http` section also different in the RR2 https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L179

**Comment by 48d90782** [comment]
4. `static` now should be in the `http` section https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L269

**Comment by Smolevich** [comment]
@48d90782, i changed config on 
 ```
 server:
  command: "php rr.php"
  env:
    XDEBUG_SESSION: 1
logs:
  encoding: json
  err_output: stderr

http:
  address: :8080
  workers:
    pool:
      numWorkers: 4
      maxJobs:  1000
  static:
    dir: "html"
    forbid: [ ".php", ".htaccess" ]

metrics:
  address: :2112

status:
  address: :2114
 ```
 And now actual error 
 ```
 {"level":"DEBUG","time":"2021/03/19 09:01:04","name":"server      ","message":"Fatal error: Uncaught Spiral\\Goridge\\Exceptions\\PrefixException: invalid prefix (checksum) in /opt/app/vendor/spiral/goridge/php-src/StreamRelay.php:126\nStack trace:\n#0 /opt/app/vendor/spiral/goridge/php-src/StreamRelay.php(86): Spiral\\Goridge\\StreamRelay->fetchPrefix()\n#1 /opt/app/vendor/spiral/roadrunner/src/Worker.php(53): Spiral\\Goridge\\StreamRelay->receiveSync(NULL)\n#2 /opt/app/vendor/spiral/roadrunner/src/HttpClient.php(39): Spiral\\RoadRunner\\Worker->receive(NULL)\n#3 /opt/app/vendor/spiral/roadrunner/src/PSR7Client.php(72): Spiral\\RoadRunner\\HttpClient->acceptRequest()\n#4 /opt/app/rr.php(53): Spiral\\RoadRunner\\PSR7Client->acceptRequest()\n#5 {main}\n  thrown in /opt/app/vendor/spiral/goridge/php-src/StreamRelay.php on line 126"}
 ```

**Comment by 48d90782** [comment]
```yaml
 workers:
   pool:
     numWorkers: 4
     maxJobs:  1000
```
https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L293

it should be:
```yaml
http:
 address: :8080
 pool:
   num_workers: 4
   max_jobs:  1000
```

By default `server` uses `pipes` as the communication protocol between RR and a worker. Please, double-check this.
