### ISSUE TITLE
[FEATURE REQUEST] Remove custom fields if rr write logs from workers 

### ISSUE THREAD

**Issue by Smolevich** [spiral/roadrunner#609]
**Is your feature request related to a problem? Please describe.**
We need to log from php side and now with RR2 logs sended to `php://stderr` looks like 
```
php-rr_1  | 2021-03-20T18:18:51.961Z    DEBUG   server  server/plugin.go:240    {"message":"custom message"} 
``` 
Settings for logs in rr config file
```
logs:
  mode: development
  encoding: console
  output: stdout
  err_output: stdout
```

**Describe the solution you'd like**
Clean log from php side 
```
{"message":"custom message"} 
```
if `encoding: console` and for mode development, production

**Comment by 48d90782** [comment]
Discussed with @wolfy-j :
1. Add new mode - `clean`
2. Update rendering

**Comment by bricelalu** [comment]
Hello @48d90782 , I have the same need, I was thinking about making the PR for this. Are you ok with that ?

In the plugin logger/config.go `BuildLogger()` I thought about adding something like this:
`	case "clean":
		zCfg = zap.Config{ // add clean config here
		}
`

What do you think ?

**Comment by 48d90782** [comment]
Hey @bricelalu, yeah sure. PRs are always very very welcome 👍🏻 
Yes, you can start from `zap.Config`. Also, keep in mind, that all logs from the worker are coming from here: https://github.com/spiral/roadrunner/blob/master/pkg/worker/worker.go#L220
And grabbed here: https://github.com/spiral/roadrunner/blob/master/plugins/server/plugin.go#L240

You can start with creating a new channel - `clean` -> https://github.com/spiral/roadrunner/blob/master/plugins/logger/plugin.go#L60

**Comment by 48d90782** [comment]
The goal of this issue is to have withing the `clean` channel a raw output to the stderr (or stdout, but specified in the config).

**Comment by bricelalu** [comment]
Hey @48d90782 ,

If I understand correctly we have a 1:1 relationship between plugins and loggers. One plugin can have his logger configured separately, the channel's name corresponding to the name of the plugin.

But if I create a `clean` channel, I should also create a `clean` plugin no ? Maybe I missed something.

**Comment by 48d90782** [comment]
Ok, let me explain :) 
We have a `BuildLogger` method with the switch over the config mode. https://github.com/spiral/roadrunner/blob/master/plugins/logger/plugin.go#L60

In this switch, you have `production`, `debug` and etc... modes for the log. I expect to have another one logger mode - `clean` which will return a configuration that will not touch the user message.

Named logger will be constructed here: https://github.com/spiral/roadrunner/blob/master/plugins/logger/plugin.go#L60. `cfg` here is the current configuration for the channel for the particular plugin.
For example, imagine we have the following config:

```yaml
# Logging settings (docs: https://roadrunner.dev/docs/beep-beep-logging)
logs:
  mode: development
  level: debug
  encoding: console
  output: stderr
  err_output: stderr
  channels:
    http:
      mode: development
      level: panic
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: production
      level: info
      encoding: json
      output: stdout
      err_output: stdout
    rpc:
      mode: production
      level: debug
      encoding: console
      output: stderr
      err_output: stdout
```
      
For the `http`, `server` and `rpc` plugins we would have a channels here: https://github.com/spiral/roadrunner/blob/master/plugins/logger/plugin.go#L61

For other plugins, we won't have channels but will have a general config  
```yaml
logs:
  mode: development
  level: debug
  encoding: console
  output: stderr
  err_output: stderr
```
and since other plugins have no channels, logger for these plugins will be constructed here: https://github.com/spiral/roadrunner/blob/master/plugins/logger/plugin.go#L69
