### ISSUE TITLE
[PLUGIN, RR2] Plugin with workers pool w/o any external endpoints like HTTP/Temporal/etc

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#633]
At the moment if a user needs to have some workers to handle some background tasks it forced to use HTTP plugin for that. But actually, user doesn't need the HTTP endpoint, only workers.
Such plugin should start, let's say, RAW PHP worker w/o any external transport like HTTP/TCP provided by the RR. Logging capabilities should be preserved and work like in the regular HTTP/Temporal plugins.

**Comment by 48d90782** [comment]
discussion: https://github.com/spiral/roadrunner/discussions/632

**Comment by 48d90782** [comment]
Discussed name with @wolfy-j : should be `service`. Like Linux/Windows daemons/services.

**Comment by 48d90782** [comment]
Config sample (draft):
```yaml
service:
   something:
     command: php something.php
     instances: 4
     restart: true
     restart_delay: 10
```
