### ISSUE TITLE
[STABILIZATION, KV] KV driver stabilization

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#640]
In the RR2 we have a generic interface for let's say KV drivers such as: `memcached`, `boltdb`, `redis`, `in-memory`.

Go interface:
```go
// Item represents general storage item
type Item struct {
	// Key of item
	Key string
	// Value of item
	Value string
	// live until time provided by TTL in RFC 3339 format
	TTL string
}

// Storage represents single abstract storage.
type Storage interface {
	// Has checks if value exists.
	Has(keys ...string) (map[string]bool, error)

	// Get loads `value` content into a byte slice.
	Get(key string) ([]byte, error)

	// MGet loads content of multiple values
	// Returns the map with existing keys and associated values
	MGet(keys ...string) (map[string]interface{}, error)

	// Set used to upload item to KV with TTL
	// 0 value in TTL means no TTL
	Set(items ...Item) error

	// MExpire sets the TTL for multiply keys
	MExpire(items ...Item) error

	// TTL return the rest time to live for provided keys
	// Not supported for the Memcached and boltdb
	TTL(keys ...string) (map[string]interface{}, error)

	// Delete one or multiple keys.
	Delete(keys ...string) error
}
```
This is a simple, generic abstraction for the different providers.

Draft for the config: `.rr.yaml`:
```yaml
kv:
  default:
    driver: memory

  boltdb-south:
    driver: boltdb
    dir: "tests/rr-bolt"
    file: "rr.db"
    bucket: "rr"
    permissions: 777
    ttl: 40s

  memcached-local:
    driver: memcached
    addr: [ "localhost:11211" ]
    
  memcached-us:
    driver: memcached
    addr: [ "us-address:11211" ]
    
  redis-10343:
     driver: redis
```

From the PHP you may use any particular KV provider by its name in the config (or all). For example, to use `boltdb-south` KV, you only need to specify its name in the PHP RPC call, like (forgive me my PHP): `kv->call(payload, response);` Payload here is the data with the specific storage type (like `boltdb-south` for example + key + value).

From the PHP perspective, the payload should contain data structure with:
1. Storage name
2. Item (key, value -> as string types, TTL as date-time string in the RFC3339 format)

All the data should be packet by the flatbuffers and passed as a binary payload.
Flatbuffers schema:
```flatbuffers
namespace generated;

table Payload {
    Storage:string;
    Items:[Item];
}

table Item {
    Key:string;
    Value:string;
    Timeout:string;
}

root_type Payload;
```
To generate PHP encoder/decoder: `flatc --php flatbuffers.fbs`

This ticket is to track progress for the KV stabilization:
- [x] Create boltdb driver
- [x] Create memcached driver
- [x] Create in-memory driver
- [x] Create redis driver
- [x] Create a general interface
- [x] Merge all drivers in the storage RPC
- [x] Tests
