### ISSUE TITLE
[BUG] static middleware of http plugin is broken on v2.2.0

### ISSUE THREAD

**Issue by tumugin** [spiral/roadrunner#669]
I tried this rr.yaml config:

```go
server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///tmp/rr-rpc.sock"
  relay: "unix:///tmp/rr-rpc.sock"
http:
  address: "0.0.0.0:9000"
  middleware: [ "static" ]
  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128
  static:
    dir: public
```

But when I start rr with `. /rr serve` to start rr, I get the following error.

```
2021-05-13T04:28:49.494+0900    WARN    http            http/serve.go:239       requested middleware does not exist     {"requested": "static"}
github.com/spiral/roadrunner/v2/plugins/http.applyMiddlewares
        github.com/spiral/roadrunner/v2@v2.2.0/plugins/http/serve.go:239
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serveHTTP
        github.com/spiral/roadrunner/v2@v2.2.0/plugins/http/serve.go:27
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serve.func2
        github.com/spiral/roadrunner/v2@v2.2.0/plugins/http/plugin.go:246
```

It works fine on v2.1.1 and is it a bug or am I doing something wrong?

My rr binary is from `./vendor/bin/rr get-binary`.

**Comment by 48d90782** [comment]
Hey @tumugin. The `static` middleware in v2.2.0 was reworked and use a little bit different configuration. You can safely delete the `static` middleware from the middleware option and use only config with the following options:
```yaml
    static:
      dir: "."
      pattern: "/tests/"
      forbid: [""]
      allow: [".txt", ".php"]
      request:
        input: "custom-header"
      response:
        output: "output-header"
```
Where a pattern is the HTTP path to the folder with the static files. It will be accessible via `http:localhost:port/tests` (for example).
