### ISSUE TITLE
[BUG] Does not start with FCGI 

### ISSUE THREAD

**Issue by alumnihabbim** [spiral/roadrunner#701]
The current configuration is: 

```yaml
server:
  # command: "php bin/console baldinof:roadrunner:worker"
  # If you are using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below.
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip"]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  fcgi:
    address: tcp://0.0.0.0:7921
logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error

```

When starting I get the following trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb3270d]

goroutine 24 [running]:
github.com/spiral/roadrunner/v2/plugins/http.applyMiddlewares(0x0, 0xc0001b61b0, 0xc0004739b0, 0x3, 0x3, 0x1586b20, 0xc0001ac050)
github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/serve.go:244 +0xad
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serveFCGI(0xc0000e5c80, 0xc0001b84e0)
github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/serve.go:76 +0x2ef
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serve.func3(0xc0000e5c80, 0xc0001b84e0)
github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/plugin.go:205 +0x35
created by github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serve
github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/plugin.go:204 +0x6f8
```
I am using a symfony 5.3 based application 
</p>
</details>
