### ISSUE TITLE
[BUG] KV boltdb permissions

### ISSUE THREAD

**Issue by SerafimArts** [spiral/roadrunner#718]
I tried this code:

```go
kv:
  first:
    driver: boltdb
    interval: 60
    file: "rr.db"
```

Then execute RR server twice:
```sh
$ rr serve
Ctrl+C (stop server)
$ rr serve
```

I expected to see this happen: All OK (default permissions is 0777)

Instead, this happened: 
```
open rr.db: Access is denied.
```

The version of RR used: `2.3.0` (stable)

Errortrace, Backtrace or Panictrace
```
←[91;1mhandle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex kv.Plugin, stopping execution, error: kv_plugin_serve:
        boltdb_plugin_provide:
        new_boltdb_driver: open rr.db: Access is denied.
←[0m
```
