### ISSUE TITLE
[BUG] KV two differend boltdb buckets in one storage

### ISSUE THREAD

**Issue by SerafimArts** [spiral/roadrunner#719]
I tried this code:

```yaml
kv:
  first:
    driver: boltdb
    interval: 60
    permissions: 0777
    file: "rr.db"
    bucket: "A"

  second:
    driver: boltdb
    interval: 60
    permissions: 0777
    file: "rr.db"
    bucket: "B"
```

I expected to see this happen: All OK

Instead, this happened: Nothing (hangs on initialization)

The version of RR used: `2.3.0` (stable)

Errortrace, Backtrace or Panictrace
```
*empty*
```
