### ISSUE TITLE
[BUG, WEBSOCKETS] Not properly handling the `Origin` header

### ISSUE THREAD

**Issue by SerafimArts** [spiral/roadrunner#727]
CORS headers are incorrectly processed.

### Configuration

```yaml
server:
    command: "php worker.php"
    relay: "pipes"

http:
    address: 127.0.0.1:80
    middleware: [ "websockets" ]

websockets:
    pubsubs: [ "memory" ]
    path: "/ws"
```

### Worker Code

```php
use Spiral\RoadRunner\Worker;
use Spiral\RoadRunner\Http\HttpWorker;

require __DIR__ . '/vendor/autoload.php';

$http = new HttpWorker(Worker::create());

while ($req = $http->waitRequest()) {
    $http->respond(200, 'Response', [
        'Access-Control-Allow-Origin' => ['*']
    ]);
}
```

### Actual Behaviour

```js
fetch('http://127.0.0.1'); // HTTP OK
new WebSocket('ws://127.0.0.1/ws'); // WebSocket connection to 'ws://127.0.0.1/ws' failed: (anonymous) | @ | VM455:1
```

*RR Trace:*

```sh
2021-06-15T23:53:52.275+0300    ?[91mERROR?[0m  ?[92mwebsockets  ?[0m   websockets/plugin.go:207        upgrade connection      {"error": "websocket: request origin not allowed by Upgrader.Ch
eckOrigin"}
github.com/spiral/roadrunner/v2/plugins/websockets.(*Plugin).Middleware.func1
        github.com/spiral/roadrunner/v2@v2.3.0/plugins/websockets/plugin.go:207
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2069
net/http.serverHandler.ServeHTTP
        net/http/server.go:2887
net/http.(*conn).serve
        net/http/server.go:1952
```

### Expected Behaviour

Correct HTTP 101 Response

### Configuration

```yaml
server:
    command: "php worker.php"
    relay: "pipes"

http:
    address: 127.0.0.1:80
    middleware: [ "headers", "websockets" ]
    headers:
        cors:
            allowed_origin: "*"

websockets:
    pubsubs: [ "memory" ]
    path: "/ws"
```

### Worker Code

```php
use Spiral\RoadRunner\Worker;
use Spiral\RoadRunner\Http\HttpWorker;

require __DIR__ . '/vendor/autoload.php';

$http = new HttpWorker(Worker::create());

while ($req = $http->waitRequest()) {
    $http->respond(200, 'Response');
}
```

### Actual Behaviour

```js
fetch('http://127.0.0.1'); // HTTP OK
new WebSocket('ws://127.0.0.1/ws'); // WebSocket connection to 'ws://127.0.0.1/ws' failed: (anonymous) | @ | VM471:1
```

*RR Trace:*

```sh
2021-06-15T23:59:12.755+0300    ?[91mERROR?[0m  ?[92mwebsockets  ?[0m   websockets/plugin.go:207        upgrade connection      {"error": "websocket: request origin not allowed by Upgrader.Ch
eckOrigin"}
github.com/spiral/roadrunner/v2/plugins/websockets.(*Plugin).Middleware.func1
        github.com/spiral/roadrunner/v2@v2.3.0/plugins/websockets/plugin.go:207
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2069
github.com/spiral/roadrunner/v2/plugins/headers.(*Plugin).Middleware.func1
        github.com/spiral/roadrunner/v2@v2.3.0/plugins/headers/plugin.go:64
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2069
net/http.serverHandler.ServeHTTP
        net/http/server.go:2887
net/http.(*conn).serve
        net/http/server.go:1952
```

### Expected Behaviour

Correct HTTP 101 Response
