### ISSUE TITLE
[BUG, WEBSOCKETS] Messages duplication

### ISSUE THREAD

**Issue by SerafimArts** [spiral/roadrunner#733]
I tried this code:

```php
RPC::create('tcp://127.0.0.1:6001')
    ->call('websockets.Publish', new Request([
        'messages' => [new Message([
            'broker' => 'memory',
            'topics' => ['topic-1', 'topic-2'],
            'payload' => 'message',
        ])]
    ]);
```

With follow config:
```yaml
rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php worker.php"
    relay: "pipes"

http:
    address: 127.0.0.1:80
    middleware: [ "websockets" ]
    pool:
        num_workers: 2

websockets:
    pubsubs: [ "memory" ]
    path: "/ws"
```

I expected to see this happen: 
```json
{"topic":"topic-1","payload":"message"}
{"topic":"topic-2","payload":"message"}
```

Instead, this happened:
```json
{"topic":"topic-1","payload":"message"}
{"topic":"topic-2","payload":"message"}
{"topic":"topic-1","payload":"message"}
{"topic":"topic-2","payload":"message"}
```

The version of RR used: `rr.exe version 2.3.1-beta.3 (build time: 2021-06-16T13:34:27+0000, go1.16.4)`

----
- The error does not depend on the number of workers in `num_workers` config section.
- The error changes its behavior if you subscribe to a different number of topics. For example, this is how the result looks for 3 channels:
```js
const ws = new WebSocket('ws://127.0.0.1/broadcast');

ws.onopen = e => {
    const message = {
        command: 'join',
        broker:  'memory',
        topics:  ['topic-1', 'topic-2', 'topic-3']
    };

    ws.send(JSON.stringify(message));
};

ws.onmessage = e => {
    const message = JSON.parse(e.data);
}
```

Then send only 1 message with payload "message" into 3 topics:

![image](https://user-images.githubusercontent.com/2461257/122457137-01bc1400-cfb7-11eb-9d16-54e8d72780d7.png)
