### ISSUE TITLE
[BUG] healthcheck return 503 whent worker TTL reached

### ISSUE THREAD

**Issue by agolodyaev** [spiral/roadrunner#734]
Hello.
In case if I use `http.pool.max_jobs` or `http.pool.supervisor.ttl` limits with nonzero values in my config file
I get healthcheck 503 error code when one of these limits was reached

The version of RR used: 2.2.1 and 2.3.0

**Comment by rustatian** [comment]
Hey @agolodyaev. Could you please share your `.rr.yaml` configuration? Do you constantly get `503` responses after `ttl` or `max_jobs`?
Please, keep in mind, that `ServiceUnavailable` is a correct response code for the healthcheck (`/health` ) endpoint in case of worker error (worker killed). To check a particular plugin (`http` in your case I guess), please, use the following URI `/health?plugin=http`)

---
Please, DO NOT skip the bug report template!

**Comment by agolodyaev** [comment]
```
rpc:
  listen: tcp://0.0.0.0:6009
metrics:
  address: 0.0.0.0:6109
status:
  address: 0.0.0.0:6409
server:
  command: "php74 worker.php"
  relay: pipes
logs:
  mode: development
  level: info
  encoding: console
  output: stderr
  err_output: stderr
http:
  address: "0.0.0.0:6209"
  pool:
    num_workers: 2
    max_jobs:    2
    allocate_timeout: 60s
    destroy_timeout:  60s
    supervisor:
      watch_tick: 1s
      ttl: 10s
      idle_ttl: 2s
      max_worker_memory: 512
      exec_ttl: 15s
```
I get 503 responses until new workers start.

How to reproduce:
1. start RR service
2. wait till TTL reached with  `WARN    server          server/plugin.go:224    worker TTL reached` message in syslog (10sec in my case)
3. check health by getting healthcheck URL `http://127.0.0.1:6409/health?plugin=http` and I get `503 Service Unavailable` 
4. Request service `http://127.0.0.1:6209` and get `ERROR   server          server/plugin.go:254    worker_watcher_wait: signal: killed; process_wait: signal: killed`  message in syslog
5. healthcheck starts working properly with `200 OK` status until either ttl or max_jobs value is reached again
