### ISSUE TITLE
[BUG] All workers ready, exec 0

### ISSUE THREAD

**Issue by iluuu1994** [spiral/roadrunner#737]
Hi! First of all, thanks for RoadRunner! :heart: It's a great tool

We have some stability issues in one of our big websites. This has occurred many times in the past and we can't identify a clear cause for what's happening. RoadRunner suddenly stops responding to requests completely after several hours or days. `rr workers` reveals that *all* of the workers are `ready` with an `EXECS` of `0`. The issue never resolves on its own until we do a `rr reset`.

I'm not sure if maybe sometimes the workers start incompletely, unable to process requests, without rr reloading them because they never reach any of the soft or hard limits. After some time they might be accumulating until there are no healthy workers left to process any requests. This is just a theory. The workers are displayed as `ready`.

The version of RR used:

> rr version 2.3.0 (build time: 2021-06-11T14:54:08+0000, go1.16.4)
 
My `.rr.yaml` configuration is:

```yaml
rpc:
  listen:     tcp://127.0.0.1:6000

server:
  command: "/usr/bin/php7.4 psr-worker.php"

http:
  address: 0.0.0.0:8082
  
  pool:
    num_workers: 48
    
    supervisor:
      watch_tick: 60s
      max_worker_memory: 200
      ttl: 84600s
      exec_ttl: 30s
```

We've just added error logging to our config now, so unfortunately I can't provide any logs yet, I will update this report as soon as we have anything.

Do you have any suspicions what might be causing this? Are there any things other than logs that we can provide that might be helpful?

Thanks for your help!
