### ISSUE TITLE
Manipulate with config using rr args `rr serve --numWorkers=1`

### ISSUE THREAD

**Issue by grachevko** [spiral/roadrunner#74]
One code can be run on different servers (dev,test,prod) with various core numbers. With this is a bad idea to hardcode workers number in config. 
For example this how we run phpunit:
```bash
paratest --processes=$(grep -c ^processor /proc/cpuinfo || 4)
```
I think it's good to be option like `rr serve --numWorkers=12` 

I also like [Traefik](https://docs.traefik.io/user-guide/cluster-docker-consul/#full-docker-compose-file) approach where every parameters can manipulate through cli options. 
```yaml
services:
  traefik:
    image: traefik:1.5
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=contact@mydomain.ca"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=mydomain.ca"
      - "--docker.watch"
```
