### ISSUE TITLE
[FEATURE REQUEST] RoadRunner 2.0, missing WS path inside the websocket pool

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#740]
When authorizing WS topics RR uses the default HTTP config. Considering that WS path defined outside of the PHP application (in RR config) it is impossible to understand if the auth request coming from the WS client or know the WS path.

In RR 1 a special ENV variable was used `RR_BROADCAST_PATH` which contained the URI path intercepted by the WebSockets middleware (same as in config).

https://github.com/spiral/roadrunner/blob/master/plugins/websockets/plugin.go#L116
https://github.com/spiral/roadrunner/blob/master/plugins/websockets/plugin.go#L168

I tried this code:

`Try to authorize the topic.`

I expected to see this happen: 

Get an ENV variable in PHP code `RR_BROADCAST_PATH`.

Instead, this happened: 

`No variable was provided.`

The version of RR used: *explanation*
  
My `.rr.yaml` configuration is: 

```yaml
rpc:
  listen: tcp://localhost:6001

server:
  command: "php app.php"

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip", "websockets" ]

  static:
    dir: "public"
    forbid: [".php", ".htaccess"]

  pool:
    num_workers: 1

websockets:
  broker: default
  path: "/ws"

broadcast:
  default:
    driver: memory

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      dirs: [ "app", "public", "../../spiral/framework" ]
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php" ]

metrics:
  address: localhost:2112
```
