### ISSUE TITLE
[RFC] Scheduled jobs

### ISSUE THREAD

**Issue by myavchik** [spiral/roadrunner#746]
Add separate simple queue (use jsondb for example) with scheduled jobs, which will send job to broker at scheduled time. Like https://github.com/mindblowup/taskq

**Comment by rustatian** [comment]
@myavchik I guess that you can solve this problem with temporal and Distributed Cron https://docs.temporal.io/docs/php/distributed-cron (RR2)

**Comment by rustatian** [comment]
You can also create a little PHP script and use `service` plugin to run it for some scheduled time periods.
https://roadrunner.dev/docs/beep-beep-service

```yaml
  some_service_1:
    command: "php scheduler.php"
    process_num: 1
    exec_timeout: 30
    remain_after_exit: true
    restart_sec: 333
```
This is not so powerful as cron, but suitable for some situations.
