### ISSUE TITLE
[FEATURE REQUEST] IPv6 Support in roadrunner 2

### ISSUE THREAD

**Issue by bramcordie** [spiral/roadrunner#767]
I'm building an app image based on the example in the [roadrunner-symfony bundle](https://github.com/Baldinof/roadrunner-bundle#usage-with-docker). The image works fine locally but our container infrastructure requires an image that listens to IPv6 traffic.

Node frameworks usually allow you to configure `::` as host when serving to force only listening for IPv6 traffic, eg: `next start -H ::`. I'm not sure if that's a possible solution here to make using 4 or 6 explicit. Listening for both like roadrunner 1 did should be fine as well.

I'm using the roadrunner config found in the [bundle repo](blob/2.x/.rr.yaml): 
```
server:
  command: "php bin/console baldinof:roadrunner:worker"
  # If you are using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below.
  # command: "php public/index.php"
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error
```
