### ISSUE TITLE
[Q] "no free workers in the pool" error on long requests

### ISSUE THREAD

**Issue by stl-victor-sudakov** [spiral/roadrunner#798]
While stress-testing a roadrunner 2.4.2 deployment under load with ApacheBench (300 concurrent connections), we encounter connection timeout errors and/or "500 internal server errors" if the query lasts more than 0.7s. The roadrunner pod logs multiple messages:

```
2021-09-15T03:17:56.900Z	WARN	server      	server/plugin.go:219	no free workers in the pool	{"error": "static_pool_exec_with_context: NoFreeWorkers:\n\tworker_watcher_get_free_worker:\n\tcontext deadline exceeded"}
```
The roadrunner is running a pretty vanilla Laravel app.

I expect to see 100% of the longer requests processed but part of the requests longer than 0.7s fail (maybe like 40% of responses are 500x or timeouts). It is even worse that only part of the requests fail and the "no free workers in the pool" error is sporadic and difficult to detect what it really depends on. 

The version of RR used: 2.4.2 from Docker Hub, running in Kubernetes v1.21
  
My `.rr.yaml` configuration is:

```
server:
  command: "php ./vendor/bin/rr-worker start"
  relay: pipes
http:
  address: 0.0.0.0:8060
  middleware: ["headers", "gzip"]
  pool:
    num_workers: 0
    max_jobs: 700
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php"]
status:
  address: 0.0.0.0:2114
```

Errortrace, Backtrace or Panictrace: Please see the attached log, not to clutter the PR. If this is a misconfiguration, please point it out.
[log.txt](https://github.com/spiral/roadrunner/files/7166666/log.txt)
