### ISSUE TITLE
[BUG]Non-root user refuses to create or use boltdb db file

### ISSUE THREAD

**Issue by Shikachuu** [spiral/roadrunner#811]
Running rr with a non-root user refuses to create the db file using key-value plugin with boltdb.

I tried this Dockerfile:
```Dockerfile
FROM spiralscout/roadrunner:2.4.1 as rr

FROM composer:2 AS autoloader
COPY . /app
WORKDIR /app
# Install composer dependencies
RUN composer install --quiet --no-scripts --optimize-autoloader --ignore-platform-reqs
# Remove sensitive informations
RUN rm auth.json custom.ini Dockerfile .rr.yaml

FROM php:8.0.10-cli-alpine3.14
RUN apk --no-cache add curl ca-certificates \
# Create a system user name app
    && addgroup -S app && adduser -S -g app app \
# Install PHP extensions for RoadRunner
    && docker-php-ext-install opcache sockets

COPY --from=autoloader /app /home/app

# Append the custom.ini to the loaded php.ini files
COPY custom.ini /usr/local/etc/php/conf.d/

# Copy the RoadRunner binary from the road runner container
COPY --from=rr /usr/bin/rr /usr/bin/rr
COPY .rr.yaml /etc/.rr.yaml

RUN chown -R app:app /home/app

WORKDIR /home/app

USER app:app

# HTTP worker endpoint
EXPOSE 8080
# Metrics endpoint
EXPOSE 2112
# Health check endpoint
EXPOSE 2114

# Checks the health endpoint with curl
HEALTHCHECK CMD curl --fail http://localhost:2114/health?plugin=http || exit 1

ENTRYPOINT ["/usr/bin/rr", "serve", "-c", "/etc/.rr.yaml"]
```

I expected to see this happen: Creates a boltdb db file to the specified location (`/home/app/rr.db`)

Instead, this happened: Breaks with permission denied error

The version of RR used: 2.4.1
  
My `.rr.yaml` configuration is:
```yaml
server:
  command: "php /home/app/index.php"

logs:
  mode: production
  encoding: json
  output: stdout

rpc:
  listen: "tcp://0.0.0.0:6001"

http:
  address: :8080
  pool:
    num_workers: 1
    max_jobs: 8

metrics:
  address: :2112

status:
  address: :2114

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/home/app" ]

kv:
  boltdb:
    driver: boltdb
    file: "rr.db"
    dir: "/home/app"
    bucket: "rr"
    interval: 86400
```

Errortrace, Backtrace or Panictrace
```
handle_serve_command: Serve error:
     endure_start:
     endure_serve_internal: Function call error:
     endure_call_serve_fn: got initial serve error from the Vertex kv.Plugin, stopping execution, error: kv_plugin_serve:
     boltdb_plugin_provide:
     new_boltdb_driver: open rr.db: permission denied
```

</p>
</details>

**Comment by rustatian** [comment]
Hey, @Shikachuu . Please, use the `permissions` key in the `boltdb` configuration. Try to set to `0644` or some other permissions suitable for you :)

**Comment by Shikachuu** [comment]
Hey, @rustatian . Thanks for the fast response!
I just tried it and still throws the same error even with `0777`.
The current config:
```yaml
kv:
  boltdb:
    driver: boltdb
    file: "rr.db"
    dir: "/home/app"
    permissions: 0777
    bucket: "rr"
    interval: 86400
```

**Comment by Shikachuu** [comment]
Even if I use a non-existing path, which should trigger a different error throws the same.
```yaml
kv:
  boltdb:
    driver: boltdb
    file: "rr.db"
    dir: "/non/existing/path"
    permissions: 0777
    bucket: "rr"
    interval: 86400
```

**Comment by rustatian** [comment]
@Shikachuu Could you please try to use `0666` ?

**Comment by Shikachuu** [comment]
> @Shikachuu Could you please try to use `0666` ?
Sure,
sadly the same error with the following kv config:
```yaml
kv:
  boltdb:
    driver: boltdb
    file: "rr.db"
    dir: "/home/app"
    permissions: 0666
    bucket: "rr"
    interval: 86400
```
