### ISSUE TITLE
[FEATURE REQUEST] More flexible static files serving

### ISSUE THREAD

**Issue by victor-sudakov** [spiral/roadrunner#816]
**Is your feature request related to a problem? Please describe.**
If I want to serve static files with different response headers, e.g. some files should have "Cache-Control: "public, max-age=300" and others "Cache-Control: no-cache" there seems no way to do it. 

**Describe the solution you'd like**
Could we have more than 1 static.dir with distinct "response" settings?

**Describe alternatives you've considered**
The only alternative is putting nginx in front of roadrunner which I don't particularly like.

**Additional context**
It would be also nice to be able to set the Expires header on static files, but it's probably another feature request already.

**Comment by rustatian** [comment]
Hey @victor-sudakov . Thanks for the proposal. We will discuss your FR. Generally, the proposed changes seem to be a good enhancement to the existing `static` plugin. So, the `static` configuration section might look like the following:
```yaml
  static:
    dir: "../../../tests"
       forbid: [""]
       allow: [".txt", ".php"]
       calculate_etag: true
       weak: true
       request:
         "input": "custom-header"
       response:
         "output": "output-header"

    dir2: "../../../tests2"
       forbid: [""]
       allow: [".txt", ".php"]
       calculate_etag: true
       weak: true
       request:
         "input": "custom-header2"
       response:
         "output": "output-header2"
```
So you would have better control over the particular static files. The main problem here is to not introduce a BC in the configuration.
