### ISSUE TITLE
[FEATURE REQUEST] Add stdout logging for service

### ISSUE THREAD

**Issue by max-kut** [spiral/roadrunner#840]
**Is your feature request related to a problem? Please describe.**
When developing a laravel project locally, the queue is started by command `php artisan queue:listen` in the service section:
```
# .rr.yaml
# Service plugin settings
service:
  queue:
    command: php artisan queue:listen --queue=default --memory=72
    process_num: 1
    exec_timeout: 0 #infinity
    remain_after_exit: true
    restart_sec: 5
```
 The queue daemon write running tasks to stdout, which can also be completed with an error. But it is impossible to see in the PP logs which tasks were completed and which ones failed.

**Describe the solution you'd like**
In the settings of the logging plugin, you can specify from which streams you want to write logs (stdout/stderr)

**Describe alternatives you've considered**
Launch different services manually on different consoles 

**Additional context**
rr v2.4.1
