### ISSUE TITLE
panic: reflect: Call using zero Value argument

### ISSUE THREAD

**Issue by ricardoee** [spiral/roadrunner#844]
I tried this code:

```go
n/a
```

I expected to see this happen: 

Unsure why I'm seeing this issue when starting RR with `exec /app/bin/rr serve -d -c /app/.rr.yaml` inside a Docker container, which I've used since `2.4.x`

Instead, this happened: See error below, but the container does start and everything works. 

The version of RR used: 2.5.3
  
My `.rr.yaml` configuration is:
```yaml
server:
  # command: "php bin/console baldinof:roadrunner:worker"
  # If you are using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below.
  command: "php public/index.php"
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: "0.0.0.0:8081"
  ssl:
    address: "0.0.0.0:8080"
    redirect: false
    cert: /app/docker/certs/cert.pem
    key: /app/docker/certs/key.pem
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
```

Errortrace, Backtrace or Panictrace
```
panic: reflect: Call using zero Value argument

goroutine 1 [running]:
reflect.Value.call({0xc000595c80, 0xc000588138, 0x0}, {0x17222dd, 0x4}, {0xc000cac660, 0x4, 0x0})
        reflect/value.go:406 +0x19db
reflect.Value.Call({0xc000595c80, 0xc000588138, 0x19a32a0}, {0xc000cac660, 0x4, 0x4})
        reflect/value.go:339 +0xc5
github.com/spiral/endure/pkg/container.(*Endure).callInitFn(0xc0000dc540, {{0x13fdc98, 0x4}, {0x0, 0x0}, {0x19a32a0, 0xc000595c80}, {0xc000595c80, 0xc000588138, 0x13}, ...}, ...)
        github.com/spiral/endure@v1.0.6/pkg/container/init.go:53 +0x133
github.com/spiral/endure/pkg/container.(*Endure).internalInit(0xc0000dc540, 0xc000c9c8f0)
        github.com/spiral/endure@v1.0.6/pkg/container/init.go:26 +0x129
github.com/spiral/endure/pkg/container.(*Endure).Initialize(0xc0000dc540)
        github.com/spiral/endure@v1.0.6/pkg/container/endure.go:398 +0x910
reflect.Value.call({0xc000695140, 0xc00000e298, 0x7f234e260108}, {0x17222dd, 0x4}, {0xc00089d3b0, 0x1, 0xc000252690})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xc000695140, 0xc00000e298, 0x0}, {0xc00089d3b0, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/spiral/endure/pkg/fsm.(*FSMImpl).Transition(0xc00089cfd8, 0x0, {0xc00007d750, 0x1, 0x5})
        github.com/spiral/endure@v1.0.6/pkg/fsm/fsm.go:180 +0x3b5
github.com/spiral/endure/pkg/container.(*Endure).Init(...)
        github.com/spiral/endure@v1.0.6/pkg/container/endure.go:308
github.com/spiral/roadrunner-binary/v2/internal/cli/serve.NewCommand.func1(0xc00013db80, {0x1722801, 0x3, 0x3})
        github.com/spiral/roadrunner-binary/v2/internal/cli/serve/command.go:52 +0x3bc
github.com/spf13/cobra.(*Command).execute(0xc00013db80, {0xc0002ffb00, 0x3, 0x3})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013c500)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.run()
        github.com/spiral/roadrunner-binary/v2/cmd/rr/main.go:22 +0x4a
main.main()
        github.com/spiral/roadrunner-binary/v2/cmd/rr/main.go:16 +0x19
```

</p>
</details>
