### ISSUE TITLE
How to avoid processing the favicon requests?

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#85]
Browsers always tries to load the `favicon.ico` file from the root. How to avoid passing these requests to PHP?

**Comment by wolfy-j** [comment]
RR passes all of non static requests to the workers, it does not contain routing logic rather than provided by static service. You can do it multiple ways:
1) put real favicon.ico
2) see @grachevko response
3) implement custom middleware on Golang end

**Comment by AlexPravdin** [comment]
@grachevko Thanks for the feedback. But using this logic we don't need the `static` config section as this functionality can be made on top of RR.

As we already have the `static` configuration it would be fine to have a list of particular files in this section that RR will not handle in addition to directory configuration.

**Comment by wolfy-j** [comment]
@AlexPravdin it already has such list, see `forbid`:

```yaml
# static file serving. remove this section to disable static file serving.
static:
  # root directory for static file (http would not serve .php and .htaccess files).
  dir:   "public"

  # list of extensions for forbid for serving.
  forbid: [".php", ".htaccess"]
```
