### ISSUE TITLE
[BUG] RR2 stop passing requests to workers

### ISSUE THREAD

**Issue by dstrop** [spiral/roadrunner#853]
we are upgrading from RR1 to RR2

after deployment everything works
and after some time (few hours) the roadrunner stops responding

I expected to see this happen:
RR keeps proccessing requests indefinitely

Instead, this happened:
RR stops passing requests to workers

the port is still open and listening to requests
```
# curl --max-time 10 -vvv 127.0.0.1:8080
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Operation timed out after 10000 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

workers are sitting idle with no execs and i can list them
```
# /usr/local/bin/rr -c '/etc/roadrunner/.rr.yaml' workers
Workers of [http]:
+---------+-----------+---------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |  CPU%   |      CREATED       |
+---------+-----------+---------+---------+---------+--------------------+
|    2379 | ready     |       0 | 28 MB   |    0.01 | 4 minutes ago      |
|    2380 | ready     |       0 | 28 MB   |    0.01 | 4 minutes ago      |
+---------+-----------+---------+---------+---------+--------------------+
```
they are rotated as they reach TTL but live past idle TTL
and calling `reset` just hangs indefinitely i can just see the rotating dots
```
Resetting plugin: [http]  ●∙∙
```
also while restarting i am not even getting the `HTTP plugin got restart request. Restarting...` info log

The version of RR used: 2.5.3
i used binary from docker image spiralscout/roadrunner:2.5.3
in php:8.0.12-cli
  
My `.rr.yaml` configuration is:
```yaml
rpc:
  enable: true
  listen: unix:///etc/roadrunner/rr.sock

server:
  command: "php -d opcache.enable_cli=1 /var/www/html/app/worker.php"
  relay: "pipes"

http:
  address: :8080

  pool:
    num_workers: 2

    supervisor:
      watch_tick: 1s # check every 1s

      # Maximal worker memory usage in megabytes (soft limit). Zero means no limit.
      max_worker_memory: 150 # 150MB
      ttl: 300s # maximum time to live for the worker (soft)
      idle_ttl: 60s # maximum allowed amount of time worker can spend in idle before being removed (for weak db connections, soft)
      exec_ttl: 360s # max_execution_time (brutal)

endure:
  log_level: info

logs:
  mode: production
  level: info

metrics:
  address: :8081
```

Errortrace, Backtrace or Panictrace
there are no errors in logs

**Comment by rustatian** [comment]
@dstrop Only one thing that looks suspicious to me is your phrase:
> they are rotated as they reach TTL but live past idle TTL

TTL is not a hard limit. If the worker has the job and it's in the working state, until it returns the response, RR will wait for it to kill. So, the TTL might be postponed.
But, if the workers are rotated even after a longer timeout, this is not a container issue (not a deadlock).

**Comment by dstrop** [comment]
i am assuming
ttl is time after which the worker will receive the stop command
idle_ttl is time since last worker exec or startup after which it will receive the stop command

if i print `rr workers`
i can see as they reach 5m (ttl is 300s) they are replaced with new workers
but idle ttl is 60s and since they are not receiving any requests even `rr workers` shows 0 execs
i would expect them to be rotated when they reach idle ttl and not live past 60s

the logs i added to php RR library showed the workers are waiting for payload and react to pid and stop commands
but there were no requests received from RR

<details>
  <summary>rr workers</summary>
  
```
# rr -c '/etc/roadrunner/.rr.yaml' workers
Workers of [http]:
+---------+-----------+---------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |  CPU%   |      CREATED       |
+---------+-----------+---------+---------+---------+--------------------+
|    1724 | ready     |       0 | 28 MB   |    0.00 | 4 minutes ago      |
|    1725 | ready     |       0 | 28 MB   |    0.01 | 4 minutes ago      |
|    1726 | ready     |       0 | 28 MB   |    0.01 | 4 minutes ago      |
|    1727 | ready     |       0 | 28 MB   |    0.02 | 3 minutes ago      |
|    1742 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1741 | ready     |       0 | 28 MB   |    0.02 | 3 minutes ago      |
|    1728 | ready     |       0 | 28 MB   |    0.02 | 3 minutes ago      |
|    1737 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1736 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1738 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1731 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1733 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1729 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1743 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1739 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1735 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1732 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1734 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1730 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1740 | ready     |       0 | 28 MB   |    0.03 | 3 minutes ago      |
|    1744 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1745 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1746 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1747 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1748 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1749 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1750 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1753 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1751 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
|    1752 | ready     |       0 | 28 MB   |    0.01 | 3 minutes ago      |
+---------+-----------+---------+---------+---------+--------------------+
```
</details>

**Comment by rustatian** [comment]
> i am assuming
ttl is time after which the worker will receive the stop command

It's a time when the worker will be:
1. Marked (not stopped) as TTL-ed if it's currently working on the request. <-- in this case, the worker may outlive the TTL time.
2. Stopped if the worker is in any state except `Working`.

> idle_ttl is time since last worker exec or startup after which it will receive the stop command

Yes, this is the time from the last processed request.

> i can see as they reach 5m (ttl is 300s) they are replaced with new workers

I need a minimum sample to reproduce the issue. Or if you are able to reproduce the problem only in your custom setup - I need a core dump.
1. `ulimit -c unlimited`
2. `GOTRACEBACK=crash ./rr ..`
After you see the problem, you may `killall -SIGSEGV rr` and send me a core dump.

**Comment by dstrop** [comment]
ahh i see now
the idle ttl issue is my misunderstanding and is unrelated to the core issue

for worker to be stoped by idle ttl it has to receive at least one request
if worker doesnt receive any request idle ttl is never triggered and worker is stoped only after reaching ttl

what i did:
i run this with the hello world worker
and sent only 1 request and watched
as the single worker reached idle timeout
but the 3 other workers lived until the TTL
where as i expected to see all 4 to be stoped by idle ttl
<details>
  <summary>.rr.yaml</summary>
  
```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"

  pool:
    num_workers: 4

    supervisor:
      max_worker_memory: 150
      ttl: 300s
      idle_ttl: 60s
      exec_ttl: 60s

logs:
  level: error
  channels:
    server:
      level: info
```
</details>
<details>
  <summary>logs</summary>
  
```
2021-11-06T19:58:14.624Z	INFO	server      	worker start time: 12.228965759277
2021-11-06T19:58:14.650Z	INFO	server      	worker start time: 12.183904647827
2021-11-06T19:58:14.675Z	INFO	server      	worker start time: 12.048959732056
2021-11-06T19:58:14.721Z	INFO	server      	worker start time: 12.854099273682
2021-11-06T19:59:23.724Z	WARN	server      	worker idle timeout reached	{"pid": 14}
2021-11-06T19:59:23.780Z	INFO	server      	worker start time: 13.642072677612
2021-11-06T20:03:14.724Z	WARN	server      	worker TTL reached	{"pid": 17}
2021-11-06T20:03:14.725Z	WARN	server      	worker TTL reached	{"pid": 18}
2021-11-06T20:03:14.730Z	WARN	server      	worker TTL reached	{"pid": 19}
2021-11-06T20:03:14.758Z	INFO	server      	worker start time: 12.322902679443
2021-11-06T20:03:14.764Z	INFO	server      	worker start time: 14.150857925415
2021-11-06T20:03:14.765Z	INFO	server      	worker start time: 13.571977615356
```
</details>

although this is little troubling as we are establishing connections on worker initialization before receiving first request
but it should not be an issue as we see enough trafic to hopefully prevent this from ever being an issue

as for the core issue i am unable to reproduce it on my machine
i am only able to observe it after deploying in test or prod
where we are running in k8s, so getting a coredump might be a challange
if you need the coredump i can try and figure it out
in the mean time i have RR deployed with --debug so i have can easily use the /debug/pprof
