### ISSUE TITLE
[BUG] Writing to php://stdout causes seg fault in worker

### ISSUE THREAD

**Issue by tezhm** [spiral/roadrunner#857]
I tried this code from inside worker:

```php
$stream = fopen('php://stdout', 'a');
fwrite($stream, 'blah');
```

I expected to see this happen: 

`'blah'` written to console.

Instead, this happened:

Worker crashes with segmentation fault and displays this error in roadrunner console:

```
sync_worker_exec_worker_with_timeout: Network:
        sync_worker_exec_payload:
        goridge_frame_receive: CRC verification failed
worker process exited
```

The version of RR used (roadrunner-binary):

```
rr version 2.5.6 (build time: 2021-11-07T19:30:36+0000, go1.17.2)
```
  
My `.rr.yaml` configuration is:

```
http:
  address: 127.0.0.1:8000
  pool:
    num_workers: 4
    max_jobs: 500
    supervisor:
      exec_ttl: 3000s
  static:
    dir: public
  middleware: [ "static" ]

server:
  command: "php -dzend_extension=xdebug.so -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 -dxdebug.start_with_request=yes -dxdebug.discover_client_host=off ./vendor/bin/roadrunner-worker"
  env:
    - APP_ENV: local
    - APP_BASE_PATH: "/home/terence/project/zencontrol-cloud/rag"
    - LARAVEL_OCTANE: "1"

rpc:
  listen: tcp://127.0.0.1:6001

logs:
  mode: development
  level: debug
  output: stdout
  encoding: console
```

</p>
</details>
