### ISSUE TITLE
[BUG] signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xd7ca3d

### ISSUE THREAD

**Issue by brzuchal** [spiral/roadrunner#867]
I tried running this:

```sh
/app # rr serve .rr.dev.yaml
{"level":"debug","ts":1638447404.4453213,"logger":"rpc","msg":"RPC plugin started","address":"tcp://127.0.0.1:6001","plugins":["informer","resetter","status"]}
[INFO] RoadRunner server started; version: 2.6.1, buildtime: 2021-12-02T09:27:17+0000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xd7ca3d]

goroutine 63 [running]:
github.com/spiral/roadrunner-plugins/v2/http.(*Plugin).workers(...)
        github.com/spiral/roadrunner-plugins/v2@v2.6.1/http/plugin.go:336
github.com/spiral/roadrunner-plugins/v2/http.(*Plugin).Workers(0xc000714160)
        github.com/spiral/roadrunner-plugins/v2@v2.6.1/http/plugin.go:320 +0xbd
github.com/spiral/roadrunner-plugins/v2/informer.(*Plugin).Workers(...)
        github.com/spiral/roadrunner-plugins/v2@v2.6.1/informer/plugin.go:33
github.com/spiral/roadrunner-plugins/v2/informer.(*rpc).Workers(0x2, {0xc00062bf80, 0x1}, 0xc000629e00)
        github.com/spiral/roadrunner-plugins/v2@v2.6.1/informer/rpc.go:31 +0x5e
reflect.Value.call({0xc0001e1500, 0xc00000f8e0, 0x13}, {0x1799a7e, 0x4}, {0xc0001f9ef8, 0x3, 0x3})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xc0001e1500, 0xc00000f8e0, 0x10}, {0xc0000686f8, 0x3, 0x3})
        reflect/value.go:339 +0xc5
net/rpc.(*service).call(0xc000334d40, 0x0, 0x0, 0xc00062b3a0, 0xc0001db380, 0xc0000687d0, {0x1526d80, 0xc0000b1ae0, 0x19ed080}, {0x15d8ee0, ...}, ...)
        net/rpc/server.go:377 +0x239
created by net/rpc.(*Server).ServeCodec
        net/rpc/server.go:474 +0x405
```

My `.rr.dev.yaml` configuration is:
```yaml
server:
    command: "php bin/console baldinof:roadrunner:worker"
    # If you are using symfony 5.3+ and the new Runtime component:
    # remove the previous `command` line above and uncomment the line below.
    # command: "php public/index.php"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
        - APP_DEBUG: 1
http:
    address: 0.0.0.0:3000
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    headers:
        cors:
            allowed_origin: "*"
            allowed_headers: "*"
            allowed_methods: "GET,POST,PUT,DELETE"
            allow_credentials: false
            exposed_headers: "Cache-Control,Content-Type"
logs:
    mode: development
    channels:
        http:
            level: info
        server:
            level: info
            mode: raw
reload:
    enabled: true
    interval: 1s
    patterns: [".php", ".yaml"]
    services:
        http:
            dirs: ["."]
            recursive: true
status:
    address: localhost:3001
rpc:
    listen: tcp://127.0.0.1:6001
```

Please instruct how can I enrich with required details.
